---
- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes